version: '3'

services:
  analytics:
    depends_on:
      - db
    build: /analytics
    ports:
      - "8080:8080" # port forwards api on localhost:8080
    networks:
      - project_network

  db: 
    # creates the database
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
    volumes:
      - db-data:/foo
      - ./scripts:/docker-entrypoint-initdb.d # creates database and tables from 'database_analytics.sql'
    ports:
      - "7070:3306" # port forwards db on localhost:7070
    networks:
      - project_network

# DATABASE TERMINAL ACCESS : mysql -u root -p -h localhost -P 7070

volumes:
  db-data:

networks:
  project_network: