version: '3'

services:

  analytics:
    build: /analytics
    ports:
      - "8080:8080"
    networks:
      - project_network

  auth:
    build: /auth
    ports:
      - '5050:5050'
    networks:
      - project_network

  frontend:
    build: /frontend/vite-project
    ports: 
      - '4173:4173'
    networks:
      - project_network

networks:
  project_network: