apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics-service
          image: "allenlizz/analytics:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"       # Minimum amount of memory allocated
              cpu: "250m"          # Minimum amount of CPU allocated
            limits:
              memory: "128Mi"      # Maximum amount of memory the container can use
              cpu: "500m"          # Maximum amount of CPU the container can use
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200