version: 1

services:
  image: "mysql:5.7"
  environment:
    MYSQL_ROOT_PASSWORD: Password123!
  volumes:
    - db-data:/foo
    - ../scripts:/docker-entrypoint-initdb.d 
  ports:
    - "3306"

volumes:
  db-data: